### ISSUE TITLE
Ajustar link "Ver perfil"

### ISSUE THREAD

**Issue by oliveiralex** [phanetcrz/github-user-search#1]
Ola Paulo, tudo bem?

Meu nome é Alexandre e estou corrigindo sua atividade. Seu trabalho foi aceito, parabéns. Para ficar 100%, sugiro que você faça o ajuste para que quando clicar no link "ver perfil" abra uma nova página com o github. Atualmente ele aparece o link mas não está direcionando.

Abraço e bons estudos!

**Comment by phanetcrz** [comment]
Boa noite Alexandre.

Infelizmente eu não consegui fazer com que o click abra uma nova aba! Pode
me ajudar nesta parte?

Em seg, 26 de abr de 2021 18:36, Alexandre ***@***.***>
escreveu:

**Comment by oliveiralex** [comment]
Olá Paulo, tudo bem?

Desculpe a demora para responder. Paulo, acredito que o ajuste seja simples para abrir em uma nova aba. Você vai ter a div para o seu botão e dentro dela você vai colocar a tag <a></a>, mais ou menos desta forma:

`<a href={userData?.html_url} target="_new">`

E dentro da tag você declara o seu <Button>.

Abraço e bons estudos
